config/routes.rb
Rails.application.routes.draw do
  resources :toris , only:[:index , :create , :edit , :update , :destroy] do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content , presence: true ,length:{maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/toris_controller.rb
class TorisController < ApplicationController
  
  before_action :set_post , only:[:edit , :update , :destroy]
  
  def index
    @posts = Post.all
    if params[:back]
      @post = Post.new(set_param)
    else
      @post = Post.new
    end
  end
  
  def create
    @post = Post.new(set_param)
    if @post.save
      redirect_to toris_path
    else
      render 'confirm'
    end
  end
  
  def confirm
    @post = Post.new(set_param)
    
    if @post.invalid?
      @posts = Post.all
      render :index
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(set_param)
      redirect_to toris_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to toris_path
  end


  private
  
  def set_param
    params.require(:post).permit(:content)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toris_helper.rb
module TorisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toriapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toris/_check_error.html.erb
<% if @post.errors.any? %>
  <div class="error_explanation">
    <p><%= @post.errors.count %>件のエラーがあります。</p>
    <ul>

    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/toris/confirm.html.erb
<div class="container">
  <header class="header">
    <%= link_to image_tag('logo.png'), toris_path ,class:"logo_image"%>
  </header>
  
  <h2>以下の内容で投稿する</h2>
  <div class="tweet-area">
    <%= form_with(model:@post , local: true ,url: toris_path, class:"tweet_form") do |form| %>
      <%= form.hidden_field :content %>
      
      <span><%= @post.content %></span>
      <div class="buttons">
        <div class="button-part">
          <%= form.submit  "送信" ,class:"tweet-button"%>
        </div>
    <% end %>
  
    <%= form_with(model:@post , local: true , url: toris_path ,method: 'get') do |form| %>
      <%= form.hidden_field :content %>
      <div class="button-part">
        <%= form.submit  "戻る" ,name: 'back',class:"tweet-buttom"%>
      </div>
      </div>
    <% end %>
  </div>

  <footer class="footer">
    <p>© 2015-2019 Copyright .</p>
  </footer>
</div>

app/views/toris/edit.html.erb
<div class="container">
  <header class="header">
    <%= link_to image_tag('logo.png'), toris_path ,class:"logo_image"%>
  </header>
  
  <h2>つぶやきなおす</h2>
  <div class="tweet-area">
    <%= form_with(model: @post, local: true , url: tori_path , class:"tweet_form") do |form| %>
  
      <%= render partial: "check_error" %>
   
      <div class="post_content">
        <!--<%= form.label :content %>-->
        <%= form.text_field :content , class:"tweet-text"%>
      </div>
      <div class="buttons">
        <div class="button-part">
          <%= form.submit "送信" ,class:"submit_button"%>
        </div>
    <% end %>
  
    <%= form_with(model:@post , local: true , url: toris_path ,method: 'get', class:"tweet_form") do |form| %>
      <%= form.hidden_field :content %>
      <div class="button-part">
        <%= form.submit  "戻る" ,name: 'back' ,class:"back_button"%>
      </div>
      </div>
    <% end %>
  </div>
   
  <footer class="footer">
    <p>© 2015-2019 Copyright .</p>
  </footer>
</div>

app/views/toris/index.html.erb
<div class="container">
  <header class="header">
    <%= link_to image_tag('logo.png'), toris_path ,class:"logo_image"%>
  </header>
  <h1>今の気持ちをつぶやこう</h1>
  
  <div class="tweet-area">
    <%= form_with(model: @post, local: true , url: confirm_toris_path, class:"tweet_form") do |form| %>
      <%= render partial: "check_error" %>
  
      <div class="post_content">
        <!--<%= form.label :content %>-->
        <%= form.text_field :content , class:"tweet-text"%>
      </div>
      
      <%= form.submit "送信"%>
    <% end %>
  </div>
    
  <h1>過去のつぶやき</h1>
  <div class="tweet-list">
    <div class="tweet-main">
      <% @posts.each do |post| %>
        <p><%= post.content %></p>
        <div class="tweet-buttoms">
          <%= link_to '編集' , edit_tori_path(post.id) ,class:"tweet-buttom"%>
          <%= link_to '削除' , tori_path(post.id), method: :delete , data:{confirm:'削除しますがよろしいですか'},class:"tweet-buttom"%>
        </div>
      <% end %>
    </div>
  </div>

  <footer class="footer">
    <p>© 2015-2019 Copyright .</p>
  </footer>
</div>